# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Start
      run: |
          if [[ `git diff --name-only HEAD~1 HEAD | grep serverless.yml` ]]; then
            yarn serverless deploy --stage development
          else
            yarn serverless deploy function -f createPayment --stage development
            yarn serverless deploy function -f updatePayment --stage development
            yarn serverless deploy function -f getPayment --stage development
            yarn serverless deploy function -f listPayments --stage development
            yarn serverless deploy function -f deletePayment --stage development
          fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
