# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop", "feature/ci" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    strategy:
      matrix:
        node-version: [14.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: yarn
    - name: Get env
      run: |
        if [ ${GITHUB_REF##*/} == "main" ]; then
          aws s3 cp s3://payments-env-vars/.env.prod .env
        else
          aws s3 cp s3://payments-env-vars/.env.dev .env
        fi
    - name: Serverless Deploy
      run: |
        yarn
        npm install -g serverless@3
        echo "${{ secrets.ENVIRONMENT_NAME }}"
        echo "$ENVIRONMENT_NAME"
        # serverless deploy --stage ${env:ENVIRONMENT_NAME}