name: Payments API - PROD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Note: commenting out line below due to this error "getCacheEntry failed: Cache service responded with 503", refer to this issue https://github.com/actions/cache/issues/820
        # cache: yarn
    - name: Get env
      run: |
        aws s3 cp s3://payments-env-vars/.env.prod .env
    - name: Serverless Deploy
      run: |
        yarn
        npm install -g serverless@3
        serverless deploy --stage $ENVIRONMENT_NAME